Спринт 10. Controllers films users
avan-es/java-filmorate pull request #3
Opened 2022-12-12 19:39 UTC by avan-es

ФЗ Спринта 10. Закончил работу над ФЗ. Тесты в Postman проходят все.

2022-12-13 07:32 UTC, LexLippi requested changes
Привет!

Неплозая работа, но не хватает тестов на валидацию, которые требуются в ТЗ!
Надо обязательно их дописать!

Желаю удачи!!!

2022-12-13 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +//    @Builder.Default
Такие комментарии оставлять не стоит

2022-12-13 18:55 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +//    @Builder.Default
Исправил!

2022-12-14 20:36 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!!!

2022-12-15 00:16 UTC, merged