ТЗ 10 Итоговый вариант
avan-es/java-filmorate pull request #6
Opened 2022-12-28 15:00 UTC by avan-es

2022-12-29 07:47 UTC, LexLippi requested changes
Привет!

Хорошая работа!
Есть несколько замечаний, которые можно поправить!

Желаю удачи!

2022-12-29 07:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +		//UserStorage inMemoryUserStorage = context.getBean(InMemoryUserStorage.class);
Такие комментарии не стоит оставлять

2022-12-29 07:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/constance/Constance.java
> +public class Constance {
1.  Не вижу большого смысла в файле с константами, если на данный момент она у нас одна. Её можно хранить по месту использования
2. Для таких файлов лучше прятать дефолтный конструктор следующим образом:

```java
private Constance() {
}
```
3. Такому классу можно добавить модификатор `final`

2022-12-29 07:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        topFilms.addAll(filmStorage.getAllFilms().values());
Можно обойтись и без `TreeSet` и кастомного компаратора. `StreamAPI` позволяет так сделать, но это не обязательно переделывать, просто стоит знать, что можно проще

2022-12-29 07:47 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
Не очень понимаю зачем в этих трех методах возвращать `Map`, кажется простого списка нам достаточно, чтобы сформировать ответ в контроллере

2022-12-29 13:53 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/constance/Constance.java
> +public class Constance {
Класс решил убрать. Добавлю в будущем, если появятся ещё константы.

2022-12-29 14:51 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        topFilms.addAll(filmStorage.getAllFilms().values());
Пробовал сделать через stream - не получается. Пока исправил ошибку - отсутствовала логика при равности getLikes().size() объектов.

2022-12-29 15:33 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
Исправил  Map<Integer, User> на List<User> в 2-х из 3-х методах:
1. getCommonFriends
2. getUserFriends

В методе getAllUsers оставил как есть. Дело в том, что я этот метод использую в классе UserValidation в методе userIdValidation - который проверяет, что пользователь с передаваемым ID существует. 

!userStorage.getAllUsers().containsKey(id)

На сколько это критично?

2022-12-29 15:36 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +		//UserStorage inMemoryUserStorage = context.getBean(InMemoryUserStorage.class);
Привет! Спасибо за проверку и отзыв 😊
Внёс все правки. Отправляю на повторную проверку. Тут написал комментарии к каждой рекомендации. Проверь, пожалуйста, комментарий к src/main/java/ru/yandex/practicum/filmorate/service/UserService.java

2022-12-29 15:37 UTC, avan-es commented
Привет! Спасибо за проверку и отзыв 😊
Внёс все правки. Отправляю на повторную проверку. Тут написал комментарии к каждой рекомендации. Проверь, пожалуйста, комментарий к src/main/java/ru/yandex/practicum/filmorate/service/UserService.java

2022-12-30 07:45 UTC, LexLippi approved these changes
Привет!

Отличная работа!
Я один комментарий оставил, его по желанию можешь к следующему спринту поправить.

Желаю удачи в наступающем году!

2022-12-30 07:45 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +		ApplicationContext context = SpringApplication.run(FilmorateApplication.class, args);
А зачем тебе сохранять контекст в переменную, если ты его потом никак не используешь?

2023-01-18 16:12 UTC, merged