Add database
avan-es/java-filmorate pull request #7
Opened 2023-02-07 01:22 UTC by avan-es

Выполнил ТЗ 11 спринта. Оказалось сложнее, чем думалось.

2023-02-07 09:35 UTC, LexLippi requested changes
Привет!

Неплохая работа!
Помимо замечаний, которые я оставил надо ещё добавить картинку схемы БД в репозиторий. Того требует ТЗ, но по ссылке я посмотрел.

Желаю удачи!

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                "Ошибка в запросе.",
1. "Ошибка в запросе" и "ошибка во введённых данных" - это по сути одно и то же.
В твоем случае - это скорее, ошибка в данных и не найден объект по запросу

2. Не вижу смысла делать разные исключения для каждой сущности, это просто увеличит количество кода для обработки ошибок, не дав существенного преимущества, при обработке

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        film.getMpa().setName(filmMpa);
Это точно необходимо при вставке?

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                SqlRowSet genreId = jdbcTemplate.queryForRowSet("SELECT GENRE_ID FROM GENRES WHERE GENRE_ID = ?", genre.getId());
1. Для такого лучше использовать оператор `exists`
2. Кажется, эту валидацию лучше производить на уровне сервиса. Запрос по вставке должен быть как можно проще

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                genre.setName(genreName);
Точно вот это надо?

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                jdbcTemplate.update(insertFilmGenre, film.getId(), genre.getId());
Можно одним запросом вставить все жанры. Это даст существенный буст по производительности

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +
Этого все можно сделать одним запросом при помощи `join`-ов

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "LIMIT ?";
На самом деле в стандарте `SQL` нет оператора `LIMIT`, реализовывать его или нет - решение каждой конкретной СУБД, поэтому я рекомендую использовать оператор `FETCH`

https://www.cybertec-postgresql.com/en/postgresql-limit-vs-fetch-first-rows-with-ties/

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    }
Лучше это все сделать одним запросом

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        return null;
Так делать не стоит. Лучше сделать возвращаемый тип `void`

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +    }
Одним запросом

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/MpaDaoImpl.java
> +    }
одним запросом

2023-02-07 09:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +public class UserDbStorage implements UserStorage {
Замечания, аналогичные `FilmStorage`

2023-02-07 09:35 UTC, LexLippi commented on src/main/resources/data.sql
> +       ('NC-17');
А если эти данные уже есть?
Лучше использовать оператор `MERGE`

2023-02-07 09:35 UTC, LexLippi commented on src/main/resources/application.properties
> +#????? ??????????? ????????? schema.sql ? data.sql
?

2023-02-07 09:35 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
К чему эта команда?

2023-02-07 09:35 UTC, LexLippi commented on src/main/resources/schema.sql
> +    RELEASE_DATE     DATE,
Он разве может быть `NULL`?

2023-02-07 09:35 UTC, LexLippi commented on src/main/resources/schema.sql
> +    FILM_DURATION    INTEGER CHECK (FILM_DURATION > 0),
Может быть `NULL`?

2023-02-07 13:31 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                "Ошибка в запросе.",
Привет! Спасибо! Буду исправлять.

Исправил. Объединил все КлассNotFound ошибки в один NotFound.

2023-02-07 13:34 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        film.getMpa().setName(filmMpa);
Ой, и без этого тесты все проходят.  Ещё учиться и учиться)
Убрал эти строки! Спасибо.

2023-02-07 14:21 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                SqlRowSet genreId = jdbcTemplate.queryForRowSet("SELECT GENRE_ID FROM GENRES WHERE GENRE_ID = ?", genre.getId());
Перенес в сервис. Как использовать exists - не понял =( Вместо этого использовал GenreIdValidation

2023-02-07 14:29 UTC, avan-es commented on src/main/resources/application.properties
> +#????? ??????????? ????????? schema.sql ? data.sql
Секретный комментарий 🙈. Кодировка глюканула🤦‍♂️. Убрал.

2023-02-07 17:53 UTC, avan-es commented on src/main/resources/data.sql
> +       ('NC-17');
Их нет, т.к. в scheme.sql я сбрасываю всю БД, чтобы при каждом запуске по новой собирать БД и стартовые данные.

2023-02-07 17:53 UTC, avan-es commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
Без этого не получается работать с тестами постмана. Нужно чистить БД. А из data.sql заполняются данные.

2023-02-07 17:55 UTC, avan-es commented on src/main/resources/schema.sql
> +    RELEASE_DATE     DATE,
Исправил.

2023-02-07 17:55 UTC, avan-es commented on src/main/resources/schema.sql
> +    FILM_DURATION    INTEGER CHECK (FILM_DURATION > 0),
Исправил.

2023-02-07 18:02 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                genre.setName(genreName);
Убрал)

2023-02-07 21:20 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +
Исправил!

2023-02-07 21:45 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                jdbcTemplate.update(insertFilmGenre, film.getId(), genre.getId());
Исправил!

2023-02-07 21:57 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                "LIMIT ?";
Заменил! Спасибо, даже не знал про FETCH FIRST ? ROWS ONLY!

2023-02-08 00:07 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    }
Готово!

2023-02-08 00:10 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        return null;
Готово!

2023-02-08 00:21 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/MpaDaoImpl.java
> +    }
Готово!

2023-02-08 00:31 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +    }
Готово!

2023-02-08 01:59 UTC, avan-es commented
Привет! В Пачке тебя не нашел, тут напишу. Я почти всё исправил, только с UserDbStorege не всё сделал (хочу запросы в getFriends и deleteFriend переделать, чтобы один был (как в FilmDbStorege ты сказал сделать)) . Но пока не успеваю. Если сможешь, посмотри, пожалуйста, правильно ли остальное поправил. Спасибо 😊

2023-02-08 06:11 UTC, LexLippi commented
Привет!
В Пачке вроде можно вот так поискать "Alexey Lipatkin", но там поиск мягко говоря так себе работает, это да :)

2023-02-08 06:24 UTC, LexLippi requested changes
Привет!

Хорошая работа!
Оставил еще несколько комментариев!

Желаю удачи!!!

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                jdbcTemplate.update(insertGenres, film.getId(), genre.getId());
Вот здесь `insert` можно одним запросом сделать, но для жтого вместо `JdbcTemplate` надо `SimpleJdbcInsertOperations` использовать. Можно конечно и с `JdbcTemplate` извратиться (динамически генерить строку с нужным количеством параметров, но это оверинжиниринг, как по мне)

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        film.getMpa().setName(mpaName);
А точно вот эти селекты нужны на жанры и рейтинг?

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        System.out.println("Hi");
Такое лучше не оставлять после отладки

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    public Map<Integer,Film> getAllFilms() {
Можно в интерфейсе возвращаемое значение на список изменить

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        List<Film> films = jdbcTemplate.query(sql, new Object[]{limit}, (rs) -> {
Там вроде есть `queryForList`

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        List<Genre> genres = new ArrayList<>();
У тебя всегда список из одного элемента получается, точно так норм?

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +        result = jdbcTemplate.query(sql, new ResultSetExtractor<List<Genre>>() {
`queryForList`

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/MpaDaoImpl.java
> +        result = jdbcTemplate.query(sql, new ResultSetExtractor<List<Mpa>>() {
`queryForList`

2023-02-08 06:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/validation/GenreValidation.java
> +                "from PUBLIC.GENRES where GENRE_ID = " + id;
Я предлагал что-то такое, так тебе не придется тащить из СЕБД целую сущность, а достаточно будет вытащить булево поле, это имеет смысл для толстых по количеству полей таблиц

```sql
select exists(select 1 from GENRES where id=?)
```

2023-02-08 20:52 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        List<Genre> genres = new ArrayList<>();
Исправил! Заодно нашел дополнительный баг - из-за которого при выгрузке всех фильмов - жанры фильмов выгружались не все, а только последний.

2023-02-08 21:00 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        System.out.println("Hi");
Готово)

2023-02-08 21:53 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +        result = jdbcTemplate.query(sql, new ResultSetExtractor<List<Genre>>() {
Готово!

2023-02-08 21:56 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/MpaDaoImpl.java
> +        result = jdbcTemplate.query(sql, new ResultSetExtractor<List<Mpa>>() {
Готово!

2023-02-08 22:29 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    public Map<Integer,Film> getAllFilms() {
Готово

2023-02-08 23:49 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +                jdbcTemplate.update(insertGenres, film.getId(), genre.getId());
Не смог разобраться с SimpleJdbcInsertOperations  =(

2023-02-09 00:11 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        film.getMpa().setName(mpaName);
Убрал.

2023-02-09 01:07 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        List<Film> films = jdbcTemplate.query(sql, new Object[]{limit}, (rs) -> {
Не получается реализовать queryForList тут =( попробую еще

2023-02-09 01:18 UTC, avan-es commented on src/main/java/ru/yandex/practicum/filmorate/validation/GenreValidation.java
> +                "from PUBLIC.GENRES where GENRE_ID = " + id;
Готово!

2023-02-09 07:09 UTC, LexLippi approved these changes
Привет!

Хорошая работа!
То, что не получилось реализовать можно попробовать реализовать к следующему спринту - необязательно, но если интересно стоит поэкспериментировать.

Желаю удачи!

2023-02-19 10:27 UTC, merged